service: documentmanager
frameworkVersion: '3'

package:
  patterns:
  - 'node_modules/**'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
 
functions:

  userRegisterService:  
    handler: src/api/userRegister.handler
    events:
      - http:
          path: user/reg
          method: post
          cors: true  

  verifyUserService:  
    handler: src/api/verifyUser.handler
    events:
      - http:
          path: user/verify
          method: post
          cors: true   

  userLoginService:  
    handler: src/api/userLogin.handler
    events:
      - http:
          path: user/login
          method: post
          cors: true 

  searchIndexService:  
    handler: src/api/searchIndex.handler
    events:
      - http:
          path: index
          method: get
          cors: true 

  addDocumentsService:
    handler: src/api/addDocuments.handler
    events:
      - http:
          path: /add/documents
          method: post
          cors: true                                                     